"""Initial StockBridge schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("user",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("full_name",sa.String(120),nullable=False),sa.Column("email",sa.String(180),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("email"));op.create_index("ix_user_email","user",["email"],unique=True)
 op.create_table("business",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("user.id"),nullable=False),sa.Column("name",sa.String(140),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_business_user_id","business",["user_id"])
 op.create_table("product",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("business_id",sa.Integer(),sa.ForeignKey("business.id"),nullable=False),sa.Column("name",sa.String(140),nullable=False),sa.Column("sku",sa.String(60)),sa.Column("category",sa.String(80)),sa.Column("buying_price",sa.Numeric(12,2),nullable=False),sa.Column("selling_price",sa.Numeric(12,2),nullable=False),sa.Column("stock_quantity",sa.Integer(),nullable=False),sa.Column("minimum_stock_level",sa.Integer(),nullable=False),sa.Column("supplier_name",sa.String(140)),sa.Column("supplier_lead_time",sa.Integer(),nullable=False),sa.Column("safety_stock",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("business_id","sku",name="uq_product_business_sku"));op.create_index("ix_product_business_id","product",["business_id"])
 op.create_table("expense",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("business_id",sa.Integer(),sa.ForeignKey("business.id"),nullable=False),sa.Column("description",sa.String(180),nullable=False),sa.Column("amount",sa.Numeric(12,2),nullable=False),sa.Column("spent_at",sa.DateTime(),nullable=False));op.create_index("ix_expense_business_id","expense",["business_id"]);op.create_index("ix_expense_spent_at","expense",["spent_at"])
 op.create_table("sale",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("business_id",sa.Integer(),sa.ForeignKey("business.id"),nullable=False),sa.Column("product_id",sa.Integer(),sa.ForeignKey("product.id"),nullable=False),sa.Column("quantity",sa.Integer(),nullable=False),sa.Column("unit_price",sa.Numeric(12,2),nullable=False),sa.Column("unit_cost",sa.Numeric(12,2),nullable=False),sa.Column("sold_at",sa.DateTime(),nullable=False));op.create_index("ix_sale_business_id","sale",["business_id"]);op.create_index("ix_sale_sold_at","sale",["sold_at"])
def downgrade():
 op.drop_table("sale");op.drop_table("expense");op.drop_table("product");op.drop_table("business");op.drop_table("user")
