"""Account trials, immutable lifetime evidence and recurring billing history."""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
revision = '0013_account_billing'
down_revision = '0012_product_catalogue'
branch_labels = None
depends_on = None

def upgrade():
    from app.subscriptions.legacy import preflight
    rows, report = preflight(op.get_bind())
    if report['multiple_lifetime_businesses'] or report['active_lifetime_without_payment_evidence']:
        raise RuntimeError('Lifetime evidence needs review; stop before enabling billing. Run the read-only billing preflight.')
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=20), nullable=False),
    sa.Column('billing_interval', sa.String(length=10), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('provider_plan_code', sa.String(length=80), nullable=False),
    sa.Column('provider_customer_code', sa.String(length=80), nullable=True),
    sa.Column('provider_subscription_code', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checkout_reference', sa.String(length=100), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('next_renewal_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('replacement_of_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['replacement_of_id'], ['recurring_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_reference'),
    sa.UniqueConstraint('provider_subscription_code'),
    sa.UniqueConstraint('replacement_of_id')
    )
    with op.batch_alter_table('recurring_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_subscription_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('billing_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=180), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('email_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['recurring_subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    with op.batch_alter_table('billing_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_event_user_id'), ['user_id'], unique=False)

    op.create_table('account_billing',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trial_eligible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trial_started_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('legacy_payment_id', sa.Integer(), nullable=True),
    sa.Column('legacy_business_id', sa.Integer(), nullable=True),
    sa.Column('legacy_granted_at', sa.DateTime(), nullable=True),
    sa.Column('primary_business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['legacy_business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['legacy_payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['primary_business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('legacy_payment_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_interval', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_payment_subscription', 'recurring_subscription', ['subscription_id'], ['id'])
        batch_op.create_foreign_key('fk_payment_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###

    account = sa.table('account_billing', sa.column('user_id',sa.Integer()),
        sa.column('trial_eligible',sa.Boolean()), sa.column('legacy_payment_id',sa.Integer()),
        sa.column('legacy_business_id',sa.Integer()), sa.column('legacy_granted_at',sa.DateTime()),
        sa.column('primary_business_id',sa.Integer()), sa.column('created_at',sa.DateTime()))
    users = op.get_bind().execute(sa.text('SELECT id FROM "user"')).scalars().all()
    evidence = {r['user_id']:r for r in rows}
    for user_id in users:
        row = evidence.get(user_id)
        primary = row['business_id'] if row else op.get_bind().execute(sa.text(
            'SELECT MIN(id) FROM business WHERE user_id=:uid'), {'uid':user_id}).scalar()
        op.get_bind().execute(account.insert().values(user_id=user_id, trial_eligible=False,
            primary_business_id=primary, legacy_payment_id=row['payment_id'] if row else None,
            legacy_business_id=row['business_id'] if row else None,
            legacy_granted_at=datetime.utcnow() if row else None, created_at=datetime.utcnow()))

def downgrade():
    raise RuntimeError('Billing/payment history is retained. Use a reviewed forward fix; destructive downgrade is disabled.')
